<?php

	$title = 'Ajouter un nouvel album';
	$this->headTitle($title);

 ?>
 <h1><?= $this->escapeHtml($title) ?></h1>
 <?php

 	$album = $form->get('title');
 	$album->setAttribute('class', 'form-control');
 	$album->setAttribute('placeholder', 'Titre de l\'album ');

 	$artist = $form->get('artist');
 	$artist->setAttribute('class', 'form-control');
 	$artist->setAttribute('placeholder', 'Artiste');

 	$submit = $form->get('submit');
 	$submit->setAttribute('class', 'btn btn-success');

	$form->setAttribute('action', $this->url('album', ['action' => 'add']));
 	$form->prepare();

 	echo $this->form()->openTag($form);

  ?>

  <div class="form-group">
  	<?= $this->formLabel($album) ?>
  	<?= $this->formElement($album) ?>
  	<?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
  </div>
  <div class="form-group">
  	<?= $this->formLabel($artist) ?>
  	<?= $this->formElement($artist) ?>
  	<?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
  </div>

<?php
	echo $this->formSubmit($form->get('submit'));
	echo $this->formHidden($form->get('id'));
 	echo $this->form()->closeTag();
 ?>