<?php
	$title = 'Mes albums';
	$this->headTitle($title);
 ?>
 <h1><?= $this->escapeHtml($title) ?> </h1>
 <p>
 	<a href="<?= $this->url('album', ['action' => 'add']) ?>">Ajouter un album</a>
 </p>
 <table class="table">
	<tr>
		<th>Titre</th>
		<th>Artiste</th>
		<th>Actions</th>
	</tr>
<?php foreach ($albums as $album) : ?>
	<tr>
		<td><?= $this->escapeHtml($album->title) ?></td>
		<td><?= $this->escapeHtml($album->artist) ?></td>
		<td>
			<a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Modifier</a>
			<a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Supprimer</a>
		</td>
	</tr>
<?php endforeach; ?>
 </table>